# Generated by Django 4.2.7 on 2023-11-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_classmodel_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='students',
            field=models.ManyToManyField(to='school.studentmodel'),
        ),
    ]
