# Generated by Django 4.2.7 on 2023-11-06 00:47

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_presenceandabsencemodel_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenceandabsencemodel',
            name='data',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
