# Generated by Django 4.2.7 on 2023-11-06 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_presenceandabsencemodel_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenceandabsencemodel',
            name='data',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
